# Generated by Django 3.2 on 2022-02-12 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер гаражу')),
                ('tariff', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Гараж',
                'verbose_name_plural': 'Гаражи',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name="Ім'я та Фамілія")),
                ('number', models.CharField(max_length=11, verbose_name='Номер телефону')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=7, null=True, verbose_name='Баланс')),
            ],
            options={
                'verbose_name': 'Орендар',
                'verbose_name_plural': 'Орендарі',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.IntegerField(verbose_name='Показник лічильника')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Сумма до оплати')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='garages.garage', verbose_name='Гараж')),
            ],
            options={
                'verbose_name': 'Показник лічильника',
                'verbose_name_plural': 'Показники лічильника',
                'ordering': ('-date',),
            },
        ),
        migrations.AddField(
            model_name='garage',
            name='renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garage', to='garages.renter', verbose_name='Орендар'),
        ),
    ]
